# Generated by Django 4.2.13 on 2024-06-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100, null=True)),
                ('document_initial', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_label', models.ManyToManyField(to='DMSApp.dokumenlabel')),
            ],
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, null=True)),
                ('department_code', models.CharField(max_length=10, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('related_document', models.ManyToManyField(to='DMSApp.dokumen')),
            ],
        ),
        migrations.CreateModel(
            name='Arsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=100, null=True)),
                ('document_no', models.CharField(max_length=100, null=True)),
                ('document_name', models.CharField(max_length=100, null=True)),
                ('effective_date', models.DateTimeField(null=True)),
                ('revision_no', models.CharField(max_length=100, null=True)),
                ('revision_date', models.DateTimeField(null=True)),
                ('part_no', models.CharField(max_length=100, null=True)),
                ('part_name', models.CharField(max_length=100, null=True)),
                ('supplier_name', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('is_inprogress', models.BooleanField(default=False, null=True)),
                ('is_rejected', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(null=True, upload_to='')),
                ('sheet_file', models.FileField(null=True, upload_to='')),
                ('other_file', models.FileField(null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('parent_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMSApp.departemen')),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMSApp.dokumen')),
            ],
        ),
    ]
