# Generated by Django 4.2.13 on 2024-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='is_inprogress',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
