# Generated by Django 4.2.13 on 2024-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='parent_department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
