# Generated by Django 4.2.13 on 2024-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0002_rename_dokumen_kategoridokumen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departemen',
            old_name='related_document',
            new_name='related_category',
        ),
        migrations.RenameField(
            model_name='kategoridokumen',
            old_name='document',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='kategoridokumen',
            old_name='document_initial',
            new_name='category_initial',
        ),
        migrations.DeleteModel(
            name='Arsip',
        ),
    ]
