# Generated by Django 4.2.13 on 2024-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0002_arsip_is_inprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
