# Generated by Django 4.2.13 on 2024-06-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0002_alter_userdetail_parent_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='parent_department',
            new_name='ldap_department',
        ),
    ]
