# Generated by Django 4.2.13 on 2024-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0003_alter_departemen_address_alter_departemen_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_ldap',
            field=models.BooleanField(default=True),
        ),
    ]
