# Generated by Django 4.2.13 on 2024-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0003_rename_parent_department_userdetail_ldap_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departemen',
            name='address',
        ),
        migrations.RemoveField(
            model_name='departemen',
            name='company',
        ),
        migrations.RemoveField(
            model_name='departemen',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='departemen',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='departemen',
            name='modified_date',
        ),
    ]
