# Generated by Django 4.2.13 on 2024-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0004_arsip_created_date_arsip_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departemen',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
