# Generated by Django 4.2.13 on 2024-06-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0004_arsip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arsip',
            new_name='FileDokumen',
        ),
    ]
