# Generated by Django 4.2.13 on 2024-06-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0005_rename_arsip_filedokumen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileDokumen',
            new_name='Dokumen',
        ),
    ]
