# Generated by Django 4.2.13 on 2024-06-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0005_alter_departemen_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departemen',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departemen',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departemen',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
