# Generated by Django 4.2.13 on 2024-06-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0006_rename_filedokumen_dokumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMSApp.dokumen')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
