# Generated by Django 4.2.13 on 2024-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0008_dokumen_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='is_inprogress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
